drop table if exists public.films cascade;
drop table if exists public.seats cascade;
drop table if exists public.tickets cascade;
drop table if exists public.sessions cascade;


CREATE TABLE public.films
(
    id       bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title    varchar(100) NOT NULL,
    duration smallint     NOT NULL,
    CONSTRAINT films_pk PRIMARY KEY (id)
);

ALTER TABLE public.films
    ADD CONSTRAINT films_un UNIQUE (title);



CREATE TABLE public.sessions
(
    id       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_at timestamp,
    price    smallint,
    film_id  bigint,
    CONSTRAINT sessions_pk PRIMARY KEY (id)
);

ALTER TABLE public.sessions
    ADD CONSTRAINT sessions_fk
        FOREIGN KEY (film_id) REFERENCES public.films (id);

CREATE TABLE public.seats
(
    id     bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    series smallint NOT NULL,
    seat   smallint NOT NULL,
    CONSTRAINT seats_pk PRIMARY KEY (id),
    CONSTRAINT seats_uk UNIQUE (series, seat)
);

CREATE TABLE public.tickets
(
    id         bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    session_id bigint NOT NULL,
    seat_id    bigint NOT NULL,
    CONSTRAINT tickets_pk PRIMARY KEY (id),
    CONSTRAINT tickets_uk UNIQUE (session_id, seat_id)
);


ALTER TABLE public.tickets
    ADD CONSTRAINT tickets_fk1
        FOREIGN KEY (session_id) REFERENCES public.sessions (id);

ALTER TABLE public.tickets
    ADD CONSTRAINT tickets_fk2
        FOREIGN KEY (seat_id) REFERENCES public.seats (id);

insert into films(title, duration)
values ('Властелин колец', 120),
       ('Шрек', 100),
       ('Громкая связь', 91),
       ('Прогулка', 96);

INSERT INTO public.sessions (start_at, price, film_id)
VALUES ('2022-08-31 09:00:00', 300, 1),
       ('2022-08-31 17:40:00', 500, 1),
       ('2022-08-31 11:10:00', 300, 2),
       ('2022-08-31 19:00:00', 500, 2),
       ('2022-08-31 12:30:00', 400, 3),
       ('2022-08-31 21:00:00', 450, 3),
       ('2022-08-31 14:32:00', 400, 4),
       ('2022-08-31 23:00:00', 350, 4);


INSERT INTO public.seats (series, seat)
values (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (2, 1),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (2, 6),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4),
       (3, 5),
       (3, 6);

INSERT INTO public.tickets (session_id, seat_id)
VALUES (1, 3),
       (1, 4),
       (1, 1),
       (2, 3),
       (2, 4),
       (2, 5),
       (2, 6),
       (2, 7),
       (2, 8),
       (3, 11),
       (3, 3),
       (3, 15),
       (3, 4),
       (4, 1),
       (4, 9),
       (4, 11),
       (4, 10),
       (4, 15),
       (4, 16),
       (5, 3),
       (5, 4),
       (5, 5),
       (5, 6),
       (5, 7),
       (5, 8),
       (6, 18),
       (6, 4),
       (6, 2),
       (6, 8),
       (6, 10),
       (6, 12),
       (7, 3),
       (7, 5),
       (7, 7),
       (7, 15),
       (7, 17),
       (8, 1),
       (8, 4),
       (8, 5);
	  